### ISSUE TITLE
Labs 1 & 3 will not build with current set of tools

### ISSUE THREAD

**Issue by cokobware** [tjvantoll/summer-of-nativescript#1]
When I try to launch Lab 1 or Lab 3 to my emulator, I get build failures.

I am using the tools listed in the Documentation for the base installation of NativeScript as of 1/20/2016.

This is the similar for Lab 1 and 3, but the following output is for Lab 3
AAPT out(1700767886) : No Delegate set : lost message:Done
AAPT err(1700767886): ERROR: 9-patch image C:\ns\summer-of-nativescript-lab\lab-3\start\platforms\android\src\main\res\drawable-nodpi\splashscreen.9.png malformed.
AAPT err(1700767886):        Must have one-pixel frame that is either transparent or white.
:processDebugManifest
:processDebugResources
C:\ns\summer-of-nativescript-lab\lab-3\start\platforms\android\src\main\res\values-v21\styles.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'AppThemeBase'.
C:\ns\summer-of-nativescript-lab\lab-3\start\platforms\android\src\main\res\values-v21\styles.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'NativeScriptToolbarStyleBase'.

Not sure how to fix?

**Comment by tjvantoll** [comment]
Hey @cokobware,

I updated the third lab as well and this seems to be running on Android alright now. If you hit anything else let me know.

Thanks!
