### ISSUE TITLE
Lab 2, Step #1 alert code not working

### ISSUE THREAD

**Issue by cokobware** [tjvantoll/summer-of-nativescript#2]
A number of students I'm working with have reported that the following code fails to show the alert and breaks:

exports.load = function(args) {
    setTimeout(function () {
            // Do something really awesome…
            // Finished doing something awesome.
            // Now let’s navigate.
            alert('Hi There!!!');
    }, 1000);
};

**Comment by tjvantoll** [comment]
Hi @cokobware,

Thanks for reporting this. I just upgraded the lab to the newest version of NativeScript and this seems to be working fine now. If you run into any other issues let me know.
